config/urls.py
"""sturdy_potato URL Configuration."""
from django.conf.urls import include, url

from potatoes import views as potatoes_views


urlpatterns = [
    url(r'^$', potatoes_views.IndexView.as_view(), name='index'),
    url(r'^farms/', include('farms.urls', namespace='farms')),
    url(r'^potatoes/', include('potatoes.urls', namespace='potatoes')),
]

farms/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^addresses/new$', views.AddressCreateView.as_view(), name='address_create'),
    url(r'^addresses/(?P<pk>[0-9]+)/$', views.AddressDetailView.as_view(), name='address_detail'),
    url(r'^addresses/get_places$', views.get_places, name='address_get_places'),
]

potatoes/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.PotatoListView.as_view(), name='list'),
    url(r'^new$', views.PotatoCreateView.as_view(), name='create'),
    url(r'^(?P<pk>[0-9]+)/$', views.PotatoDetailView.as_view(), name='detail'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Sturdy Potato - Django sample code</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
</head>
<body>

<div class="container">

    {% block content %}
    {% endblock content %}

</div> <!-- /.container -->

{% block javascript %}
<!-- jQuery first, then Tether, then Bootstrap JS. -->
<script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
{% endblock javascript %}

</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}

<h1>Sturdy Potato</h1>

<ul>
    <li><a href="{% url 'potatoes:list' %}">List of all potatoes</a></li>
    <li><a href="{% url 'potatoes:create' %}">Create a new potato</a></li>
</ul>

<h2>Farms</h2>
<ul>
    <li><a href="{% url 'farms:address_create' %}">Add an address!</a></li>
</ul>

{% endblock content %}